# Site settings
title: Eric Chan
description: A blog about my life and work
baseurl: "" # the subpath of your site, e.g. /blog
url: "localhost:4000" # the base hostname & protocol for your site e.g. http://willianjusten.com.br

# User settings
username: Eric
user_description: I'm a data analytics student at University of Technology, Sydney. I am very interested in  <b>Data Analytics</b> . Visit my blog here <a href="http://ericc.me" target="_blank">http://ericc.me</a>
user_title: Data Analytics Student
email: eric.chan
# twitter_username: lorem_ipsum
github_username: ec2908
# gplus_username:  lorem_ipsum

# Google-analytics
google-analytics:
  id: ""

exclude: ['package.json', 'src' , 'node_modules']
